# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Tests"
    lane :tests_latest do
    run_tests(
        workspace: "CaffeineTimer.xcworkspace",
        scheme: "CaffeineTimer",
        devices: [
            # "iPhone 6 (10.3.1)",
            # "iPad Air (9.3)",
            # "iPhone 7 Plus (10.3.1)",
            # "iPad Pro (12.9 inch) (10.3.1)",
            # "iPhone X (11.4)",
            # "iPad Pro (10.5-inch) (11.4)",
            "iPhone 11 Pro Max"
        ],
        disable_concurrent_testing: true,
        configuration: 'Debug'
    )
    end
end
